In [36]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [57]:
# Importing Libraries
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from statsmodels import api as sm
import numpy as np
from tqdm import tqdm

In [38]:
# Importing the dataset
df=pd.read_csv('/content/drive/MyDrive/DA2023/train.csv')

In [39]:
# Filling null values in 'Id' column
for i in df.columns[2:]:
  df[i] = df[i].fillna(df["Id"])

In [40]:
# Making 'target' dataframe
target = df[df["Time"].isna()]["Sensor_1"].reset_index(drop=True)

In [41]:
# Dropping irrelevant columns
df.pop('Id')
df.pop('Time')

0          1.0
1          2.0
2          3.0
3          4.0
4          5.0
          ... 
549995     7.0
549996     8.0
549997     9.0
549998    10.0
549999     NaN
Name: Time, Length: 550000, dtype: float64

In [42]:
# Checking columns left in training data
df.columns

Index(['Sensor_1', 'Sensor_2', 'Sensor_3', 'Sensor_4', 'Sensor_5', 'Sensor_6',
       'Sensor_7', 'Sensor_8', 'Sensor_9', 'Sensor_10', 'Sensor_11',
       'Sensor_12', 'Sensor_13', 'Sensor_14', 'Sensor_15', 'Sensor_16',
       'Sensor_17', 'Sensor_18', 'Sensor_19', 'Sensor_20', 'Sensor_21',
       'Sensor_22', 'Sensor_23', 'Sensor_24', 'Sensor_25'],
      dtype='object')

In [43]:
# Preparing training set
sequences_train = list()
for i in range(0,30000):
    df_temp = df.iloc[(i*11):((i+1)*11)-1]
    values = df_temp.values
    values = values.transpose()
    sequences_train.append(values)

target_train=target[0:30000]

In [44]:
# Preparing target dataframe of training set
sequences_test = list()
for i in range(30000,40000):
    df_temp = df.iloc[(i*11):((i+1)*11)-1]
    values = df_temp.values
    values = values.transpose()
    sequences_test.append(values)

target_test=target[30000:40000]

In [45]:
# Size of dataset
len(df)

550000

In [46]:
# Preparing validation set
sequences_val = list()
for i in range(40000,49500):
    df_temp = df.iloc[(i*11):((i+1)*11)-1]
    values = df_temp.values
    values = values.transpose()
    sequences_val.append(values)

target_val=target[40000:49500]

In [47]:
# Converting them into array for fitting into LSTM model
sequence_train=np.array(sequences_train)
sequence_test=np.array(sequences_test)
sequence_val=np.array(sequences_val)

In [48]:
# Importing required DL libraries
from keras.preprocessing import sequence
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.optimizers import Adam
from keras.models import load_model
from keras.callbacks import ModelCheckpoint
from keras.utils import to_categorical
from keras.layers import TimeDistributed
from keras.layers import Bidirectional

In [49]:
# Converting targets of all sets to categorical
targets_train=to_categorical(target_train, num_classes=4)
targets_test=to_categorical(target_test, num_classes=4)
targets_val=to_categorical(target_val, num_classes=4)

In [50]:
# Preparing model
model = Sequential()
model.add(Bidirectional(LSTM(64, return_sequences=True, input_shape=(25, 10))))
#model.add(BatchNormalization())
model.add(Bidirectional(LSTM(64, return_sequences=True))) # returns a sequence of vectors of dimension 32
#model.add(BatchNormalization())
model.add(Bidirectional(LSTM(32, return_sequences=True)))  # returns a sequence of vectors of dimension 32
#model.add(BatchNormalization())
model.add(Bidirectional(LSTM(32)))
#model.add(BatchNormalization())
model.add(Dense(4, activation='softmax'))

In [51]:
# Fitting model
adam = Adam(lr=0.001)
chk = ModelCheckpoint('best_model.pkl', monitor='val_acc', save_best_only=True, mode='max', verbose=1)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
model.fit(sequence_train, targets_train, epochs=100, batch_size=128, callbacks=[chk], validation_data=(sequence_val,targets_val))

Epoch 1/100
235/235 [==============================] - ETA: 0s - loss: 1.3746 - accuracy: 0.2941

235/235 [==============================] - 98s 330ms/step - loss: 1.3746 - accuracy: 0.2941 - val_loss: 1.3645 - val_accuracy: 0.3028
Epoch 2/100
235/235 [==============================] - ETA: 0s - loss: 1.3351 - accuracy: 0.3390

235/235 [==============================] - 68s 289ms/step - loss: 1.3351 - accuracy: 0.3390 - val_loss: 1.3027 - val_accuracy: 0.3674
Epoch 3/100
235/235 [==============================] - ETA: 0s - loss: 1.2971 - accuracy: 0.3702

235/235 [==============================] - 66s 279ms/step - loss: 1.2971 - accuracy: 0.3702 - val_loss: 1.2594 - val_accuracy: 0.3973
Epoch 4/100
235/235 [==============================] - ETA: 0s - loss: 1.1482 - accuracy: 0.4582

235/235 [==============================] - 71s 303ms/step - loss: 1.1482 - accuracy: 0.4582 - val_loss: 1.0773 - val_accuracy: 0.5023
Epoch 5/100
235/235 [==============================] - ETA: 0s - loss: 0.9275 - accuracy: 0.5748

235/235 [==============================] - 67s 287ms/step - loss: 0.9275 - accuracy: 0.5748 - val_loss: 1.0904 - val_accuracy: 0.4726
Epoch 6/100
235/235 [==============================] - ETA: 0s - loss: 0.7976 - accuracy: 0.6385

235/235 [==============================] - 71s 303ms/step - loss: 0.7976 - accuracy: 0.6385 - val_loss: 0.6723 - val_accuracy: 0.7041
Epoch 7/100
235/235 [==============================] - ETA: 0s - loss: 0.6297 - accuracy: 0.7216

235/235 [==============================] - 68s 288ms/step - loss: 0.6297 - accuracy: 0.7216 - val_loss: 0.6072 - val_accuracy: 0.7271
Epoch 8/100
235/235 [==============================] - ETA: 0s - loss: 0.5415 - accuracy: 0.7642

235/235 [==============================] - 68s 288ms/step - loss: 0.5415 - accuracy: 0.7642 - val_loss: 0.5251 - val_accuracy: 0.7737
Epoch 9/100
235/235 [==============================] - ETA: 0s - loss: 0.4835 - accuracy: 0.7894

235/235 [==============================] - 72s 305ms/step - loss: 0.4835 - accuracy: 0.7894 - val_loss: 0.4871 - val_accuracy: 0.7896
Epoch 10/100
235/235 [==============================] - ETA: 0s - loss: 0.4424 - accuracy: 0.8088

235/235 [==============================] - 66s 280ms/step - loss: 0.4424 - accuracy: 0.8088 - val_loss: 0.4132 - val_accuracy: 0.8186
Epoch 11/100
235/235 [==============================] - ETA: 0s - loss: 0.4012 - accuracy: 0.8270

235/235 [==============================] - 72s 308ms/step - loss: 0.4012 - accuracy: 0.8270 - val_loss: 0.4282 - val_accuracy: 0.8117
Epoch 12/100
235/235 [==============================] - ETA: 0s - loss: 0.3839 - accuracy: 0.8352

235/235 [==============================] - 66s 280ms/step - loss: 0.3839 - accuracy: 0.8352 - val_loss: 0.3918 - val_accuracy: 0.8296
Epoch 13/100
235/235 [==============================] - ETA: 0s - loss: 0.3402 - accuracy: 0.8533

235/235 [==============================] - 67s 288ms/step - loss: 0.3402 - accuracy: 0.8533 - val_loss: 0.5010 - val_accuracy: 0.7764
Epoch 14/100
235/235 [==============================] - ETA: 0s - loss: 0.3366 - accuracy: 0.8554

235/235 [==============================] - 71s 302ms/step - loss: 0.3366 - accuracy: 0.8554 - val_loss: 0.4243 - val_accuracy: 0.8095
Epoch 15/100
235/235 [==============================] - ETA: 0s - loss: 0.2979 - accuracy: 0.8720

235/235 [==============================] - 67s 287ms/step - loss: 0.2979 - accuracy: 0.8720 - val_loss: 0.3413 - val_accuracy: 0.8515
Epoch 16/100
235/235 [==============================] - ETA: 0s - loss: 0.2857 - accuracy: 0.8787

235/235 [==============================] - 67s 286ms/step - loss: 0.2857 - accuracy: 0.8787 - val_loss: 0.3284 - val_accuracy: 0.8557
Epoch 17/100
235/235 [==============================] - ETA: 0s - loss: 0.2582 - accuracy: 0.8897

235/235 [==============================] - 64s 270ms/step - loss: 0.2582 - accuracy: 0.8897 - val_loss: 0.2407 - val_accuracy: 0.8969
Epoch 18/100
235/235 [==============================] - ETA: 0s - loss: 0.2564 - accuracy: 0.8895

235/235 [==============================] - 65s 279ms/step - loss: 0.2564 - accuracy: 0.8895 - val_loss: 0.2864 - val_accuracy: 0.8759
Epoch 19/100
235/235 [==============================] - ETA: 0s - loss: 0.2429 - accuracy: 0.8964

235/235 [==============================] - 69s 294ms/step - loss: 0.2429 - accuracy: 0.8964 - val_loss: 0.2761 - val_accuracy: 0.8763
Epoch 20/100
235/235 [==============================] - ETA: 0s - loss: 0.2399 - accuracy: 0.8995

235/235 [==============================] - 67s 287ms/step - loss: 0.2399 - accuracy: 0.8995 - val_loss: 0.2251 - val_accuracy: 0.9008
Epoch 21/100
235/235 [==============================] - ETA: 0s - loss: 0.2164 - accuracy: 0.9086

235/235 [==============================] - 68s 288ms/step - loss: 0.2164 - accuracy: 0.9086 - val_loss: 0.2738 - val_accuracy: 0.8805
Epoch 22/100
235/235 [==============================] - ETA: 0s - loss: 0.2048 - accuracy: 0.9117

235/235 [==============================] - 71s 304ms/step - loss: 0.2048 - accuracy: 0.9117 - val_loss: 0.2194 - val_accuracy: 0.9059
Epoch 23/100
235/235 [==============================] - ETA: 0s - loss: 0.2084 - accuracy: 0.9103

235/235 [==============================] - 66s 280ms/step - loss: 0.2084 - accuracy: 0.9103 - val_loss: 0.2183 - val_accuracy: 0.9080
Epoch 24/100
235/235 [==============================] - ETA: 0s - loss: 0.2026 - accuracy: 0.9151

235/235 [==============================] - 71s 301ms/step - loss: 0.2026 - accuracy: 0.9151 - val_loss: 0.2049 - val_accuracy: 0.9142
Epoch 25/100
235/235 [==============================] - ETA: 0s - loss: 0.1872 - accuracy: 0.9209

235/235 [==============================] - 68s 290ms/step - loss: 0.1872 - accuracy: 0.9209 - val_loss: 0.1973 - val_accuracy: 0.9173
Epoch 26/100
235/235 [==============================] - ETA: 0s - loss: 0.2063 - accuracy: 0.9123

235/235 [==============================] - 68s 289ms/step - loss: 0.2063 - accuracy: 0.9123 - val_loss: 0.1973 - val_accuracy: 0.9168
Epoch 27/100
235/235 [==============================] - ETA: 0s - loss: 0.1757 - accuracy: 0.9261

235/235 [==============================] - 72s 306ms/step - loss: 0.1757 - accuracy: 0.9261 - val_loss: 0.1851 - val_accuracy: 0.9181
Epoch 28/100
235/235 [==============================] - ETA: 0s - loss: 0.1710 - accuracy: 0.9272

235/235 [==============================] - 66s 281ms/step - loss: 0.1710 - accuracy: 0.9272 - val_loss: 0.2107 - val_accuracy: 0.9109
Epoch 29/100
235/235 [==============================] - ETA: 0s - loss: 0.1742 - accuracy: 0.9260

235/235 [==============================] - 68s 290ms/step - loss: 0.1742 - accuracy: 0.9260 - val_loss: 0.1975 - val_accuracy: 0.9137
Epoch 30/100
235/235 [==============================] - ETA: 0s - loss: 0.1755 - accuracy: 0.9262

235/235 [==============================] - 73s 311ms/step - loss: 0.1755 - accuracy: 0.9262 - val_loss: 0.2119 - val_accuracy: 0.9093
Epoch 31/100
235/235 [==============================] - ETA: 0s - loss: 0.1631 - accuracy: 0.9297

235/235 [==============================] - 71s 303ms/step - loss: 0.1631 - accuracy: 0.9297 - val_loss: 0.2637 - val_accuracy: 0.8887
Epoch 32/100
235/235 [==============================] - ETA: 0s - loss: 0.1600 - accuracy: 0.9333

235/235 [==============================] - 74s 316ms/step - loss: 0.1600 - accuracy: 0.9333 - val_loss: 0.1617 - val_accuracy: 0.9295
Epoch 33/100
235/235 [==============================] - ETA: 0s - loss: 0.1493 - accuracy: 0.9396

235/235 [==============================] - 66s 282ms/step - loss: 0.1493 - accuracy: 0.9396 - val_loss: 0.1493 - val_accuracy: 0.9361
Epoch 34/100
235/235 [==============================] - ETA: 0s - loss: 0.1769 - accuracy: 0.9247

235/235 [==============================] - 70s 299ms/step - loss: 0.1769 - accuracy: 0.9247 - val_loss: 0.2333 - val_accuracy: 0.9011
Epoch 35/100
235/235 [==============================] - ETA: 0s - loss: 0.1542 - accuracy: 0.9337

235/235 [==============================] - 70s 297ms/step - loss: 0.1542 - accuracy: 0.9337 - val_loss: 0.1571 - val_accuracy: 0.9325
Epoch 36/100
235/235 [==============================] - ETA: 0s - loss: 0.1435 - accuracy: 0.9401

235/235 [==============================] - 69s 292ms/step - loss: 0.1435 - accuracy: 0.9401 - val_loss: 0.2007 - val_accuracy: 0.9138
Epoch 37/100
235/235 [==============================] - ETA: 0s - loss: 0.1551 - accuracy: 0.9353

235/235 [==============================] - 74s 315ms/step - loss: 0.1551 - accuracy: 0.9353 - val_loss: 0.1673 - val_accuracy: 0.9288
Epoch 38/100
235/235 [==============================] - ETA: 0s - loss: 0.1562 - accuracy: 0.9335

235/235 [==============================] - 66s 283ms/step - loss: 0.1562 - accuracy: 0.9335 - val_loss: 0.1768 - val_accuracy: 0.9261
Epoch 39/100
235/235 [==============================] - ETA: 0s - loss: 0.1356 - accuracy: 0.9428

235/235 [==============================] - 71s 301ms/step - loss: 0.1356 - accuracy: 0.9428 - val_loss: 0.2344 - val_accuracy: 0.8991
Epoch 40/100
235/235 [==============================] - ETA: 0s - loss: 0.1332 - accuracy: 0.9439

235/235 [==============================] - 70s 297ms/step - loss: 0.1332 - accuracy: 0.9439 - val_loss: 0.1787 - val_accuracy: 0.9227
Epoch 41/100
235/235 [==============================] - ETA: 0s - loss: 0.1335 - accuracy: 0.9453

235/235 [==============================] - 66s 283ms/step - loss: 0.1335 - accuracy: 0.9453 - val_loss: 0.1422 - val_accuracy: 0.9383
Epoch 42/100
235/235 [==============================] - ETA: 0s - loss: 0.1422 - accuracy: 0.9416

235/235 [==============================] - 70s 297ms/step - loss: 0.1422 - accuracy: 0.9416 - val_loss: 0.1808 - val_accuracy: 0.9232
Epoch 43/100
235/235 [==============================] - ETA: 0s - loss: 0.1233 - accuracy: 0.9495

235/235 [==============================] - 68s 291ms/step - loss: 0.1233 - accuracy: 0.9495 - val_loss: 0.1781 - val_accuracy: 0.9254
Epoch 44/100
235/235 [==============================] - ETA: 0s - loss: 0.1398 - accuracy: 0.9399

235/235 [==============================] - 68s 289ms/step - loss: 0.1398 - accuracy: 0.9399 - val_loss: 0.1874 - val_accuracy: 0.9202
Epoch 45/100
235/235 [==============================] - ETA: 0s - loss: 0.1333 - accuracy: 0.9448

235/235 [==============================] - 72s 305ms/step - loss: 0.1333 - accuracy: 0.9448 - val_loss: 0.1818 - val_accuracy: 0.9206
Epoch 46/100
235/235 [==============================] - ETA: 0s - loss: 0.1319 - accuracy: 0.9453

235/235 [==============================] - 66s 282ms/step - loss: 0.1319 - accuracy: 0.9453 - val_loss: 0.2229 - val_accuracy: 0.9101
Epoch 47/100
235/235 [==============================] - ETA: 0s - loss: 0.1226 - accuracy: 0.9504

235/235 [==============================] - 68s 290ms/step - loss: 0.1226 - accuracy: 0.9504 - val_loss: 0.1794 - val_accuracy: 0.9246
Epoch 48/100
235/235 [==============================] - ETA: 0s - loss: 0.1219 - accuracy: 0.9489

235/235 [==============================] - 73s 309ms/step - loss: 0.1219 - accuracy: 0.9489 - val_loss: 0.2393 - val_accuracy: 0.9003
Epoch 49/100
235/235 [==============================] - ETA: 0s - loss: 0.1274 - accuracy: 0.9467

235/235 [==============================] - 70s 299ms/step - loss: 0.1274 - accuracy: 0.9467 - val_loss: 0.1906 - val_accuracy: 0.9256
Epoch 50/100
235/235 [==============================] - ETA: 0s - loss: 0.1231 - accuracy: 0.9497

235/235 [==============================] - 70s 297ms/step - loss: 0.1231 - accuracy: 0.9497 - val_loss: 0.1782 - val_accuracy: 0.9241
Epoch 51/100
235/235 [==============================] - ETA: 0s - loss: 0.1241 - accuracy: 0.9478

235/235 [==============================] - 66s 283ms/step - loss: 0.1241 - accuracy: 0.9478 - val_loss: 0.1686 - val_accuracy: 0.9276
Epoch 52/100
235/235 [==============================] - ETA: 0s - loss: 0.1166 - accuracy: 0.9503

235/235 [==============================] - 66s 282ms/step - loss: 0.1166 - accuracy: 0.9503 - val_loss: 0.1580 - val_accuracy: 0.9347
Epoch 53/100
235/235 [==============================] - ETA: 0s - loss: 0.1164 - accuracy: 0.9518

235/235 [==============================] - 71s 304ms/step - loss: 0.1164 - accuracy: 0.9518 - val_loss: 0.1461 - val_accuracy: 0.9373
Epoch 54/100
235/235 [==============================] - ETA: 0s - loss: 0.1179 - accuracy: 0.9529

235/235 [==============================] - 68s 288ms/step - loss: 0.1179 - accuracy: 0.9529 - val_loss: 0.1754 - val_accuracy: 0.9254
Epoch 55/100
235/235 [==============================] - ETA: 0s - loss: 0.1064 - accuracy: 0.9564

235/235 [==============================] - 68s 290ms/step - loss: 0.1064 - accuracy: 0.9564 - val_loss: 0.2396 - val_accuracy: 0.9085
Epoch 56/100
235/235 [==============================] - ETA: 0s - loss: 0.1141 - accuracy: 0.9531

235/235 [==============================] - 74s 313ms/step - loss: 0.1141 - accuracy: 0.9531 - val_loss: 0.1723 - val_accuracy: 0.9283
Epoch 57/100
235/235 [==============================] - ETA: 0s - loss: 0.1159 - accuracy: 0.9518

235/235 [==============================] - 66s 283ms/step - loss: 0.1159 - accuracy: 0.9518 - val_loss: 0.1980 - val_accuracy: 0.9199
Epoch 58/100
235/235 [==============================] - ETA: 0s - loss: 0.1059 - accuracy: 0.9582

235/235 [==============================] - 72s 307ms/step - loss: 0.1059 - accuracy: 0.9582 - val_loss: 0.1525 - val_accuracy: 0.9362
Epoch 59/100
235/235 [==============================] - ETA: 0s - loss: 0.1235 - accuracy: 0.9506

235/235 [==============================] - 68s 291ms/step - loss: 0.1235 - accuracy: 0.9506 - val_loss: 0.2369 - val_accuracy: 0.9049
Epoch 60/100
235/235 [==============================] - ETA: 0s - loss: 0.1114 - accuracy: 0.9528

235/235 [==============================] - 67s 287ms/step - loss: 0.1114 - accuracy: 0.9528 - val_loss: 0.1764 - val_accuracy: 0.9271
Epoch 61/100
235/235 [==============================] - ETA: 0s - loss: 0.1037 - accuracy: 0.9569

235/235 [==============================] - 71s 304ms/step - loss: 0.1037 - accuracy: 0.9569 - val_loss: 0.1553 - val_accuracy: 0.9357
Epoch 62/100
235/235 [==============================] - ETA: 0s - loss: 0.1008 - accuracy: 0.9609

235/235 [==============================] - 68s 289ms/step - loss: 0.1008 - accuracy: 0.9609 - val_loss: 0.2058 - val_accuracy: 0.9214
Epoch 63/100
235/235 [==============================] - ETA: 0s - loss: 0.1164 - accuracy: 0.9517

235/235 [==============================] - 72s 307ms/step - loss: 0.1164 - accuracy: 0.9517 - val_loss: 0.1860 - val_accuracy: 0.9216
Epoch 64/100
235/235 [==============================] - ETA: 0s - loss: 0.0989 - accuracy: 0.9609

235/235 [==============================] - 69s 293ms/step - loss: 0.0989 - accuracy: 0.9609 - val_loss: 0.1533 - val_accuracy: 0.9369
Epoch 65/100
235/235 [==============================] - ETA: 0s - loss: 0.0966 - accuracy: 0.9602

235/235 [==============================] - 66s 279ms/step - loss: 0.0966 - accuracy: 0.9602 - val_loss: 0.2347 - val_accuracy: 0.9087
Epoch 66/100
235/235 [==============================] - ETA: 0s - loss: 0.0909 - accuracy: 0.9625

235/235 [==============================] - 71s 304ms/step - loss: 0.0909 - accuracy: 0.9625 - val_loss: 0.1642 - val_accuracy: 0.9316
Epoch 67/100
235/235 [==============================] - ETA: 0s - loss: 0.1220 - accuracy: 0.9501

235/235 [==============================] - 68s 289ms/step - loss: 0.1220 - accuracy: 0.9501 - val_loss: 0.1670 - val_accuracy: 0.9317
Epoch 68/100
235/235 [==============================] - ETA: 0s - loss: 0.0911 - accuracy: 0.9634

235/235 [==============================] - 67s 286ms/step - loss: 0.0911 - accuracy: 0.9634 - val_loss: 0.2323 - val_accuracy: 0.9118
Epoch 69/100
235/235 [==============================] - ETA: 0s - loss: 0.0989 - accuracy: 0.9599

235/235 [==============================] - 71s 301ms/step - loss: 0.0989 - accuracy: 0.9599 - val_loss: 0.2043 - val_accuracy: 0.9209
Epoch 70/100
235/235 [==============================] - ETA: 0s - loss: 0.0900 - accuracy: 0.9632

235/235 [==============================] - 62s 262ms/step - loss: 0.0900 - accuracy: 0.9632 - val_loss: 0.1685 - val_accuracy: 0.9300
Epoch 71/100
235/235 [==============================] - ETA: 0s - loss: 0.1011 - accuracy: 0.9594

235/235 [==============================] - 64s 271ms/step - loss: 0.1011 - accuracy: 0.9594 - val_loss: 0.2314 - val_accuracy: 0.9080
Epoch 72/100
235/235 [==============================] - ETA: 0s - loss: 0.1158 - accuracy: 0.9532

235/235 [==============================] - 61s 260ms/step - loss: 0.1158 - accuracy: 0.9532 - val_loss: 0.2831 - val_accuracy: 0.8895
Epoch 73/100
235/235 [==============================] - ETA: 0s - loss: 0.0850 - accuracy: 0.9671

235/235 [==============================] - 61s 260ms/step - loss: 0.0850 - accuracy: 0.9671 - val_loss: 0.1677 - val_accuracy: 0.9307
Epoch 74/100
235/235 [==============================] - ETA: 0s - loss: 0.0926 - accuracy: 0.9629

235/235 [==============================] - 64s 272ms/step - loss: 0.0926 - accuracy: 0.9629 - val_loss: 0.2015 - val_accuracy: 0.9185
Epoch 75/100
235/235 [==============================] - ETA: 0s - loss: 0.0917 - accuracy: 0.9636

235/235 [==============================] - 61s 260ms/step - loss: 0.0917 - accuracy: 0.9636 - val_loss: 0.1590 - val_accuracy: 0.9353
Epoch 76/100
235/235 [==============================] - ETA: 0s - loss: 0.0962 - accuracy: 0.9601

235/235 [==============================] - 61s 262ms/step - loss: 0.0962 - accuracy: 0.9601 - val_loss: 0.1959 - val_accuracy: 0.9232
Epoch 77/100
235/235 [==============================] - ETA: 0s - loss: 0.0825 - accuracy: 0.9669

235/235 [==============================] - 64s 273ms/step - loss: 0.0825 - accuracy: 0.9669 - val_loss: 0.1729 - val_accuracy: 0.9316
Epoch 78/100
235/235 [==============================] - ETA: 0s - loss: 0.0837 - accuracy: 0.9664

235/235 [==============================] - 61s 260ms/step - loss: 0.0837 - accuracy: 0.9664 - val_loss: 0.4368 - val_accuracy: 0.8720
Epoch 79/100
235/235 [==============================] - ETA: 0s - loss: 0.0886 - accuracy: 0.9642

235/235 [==============================] - 61s 261ms/step - loss: 0.0886 - accuracy: 0.9642 - val_loss: 0.1908 - val_accuracy: 0.9276
Epoch 80/100
235/235 [==============================] - ETA: 0s - loss: 0.0820 - accuracy: 0.9673

235/235 [==============================] - 69s 295ms/step - loss: 0.0820 - accuracy: 0.9673 - val_loss: 0.1738 - val_accuracy: 0.9305
Epoch 81/100
235/235 [==============================] - ETA: 0s - loss: 0.0966 - accuracy: 0.9623

235/235 [==============================] - 64s 272ms/step - loss: 0.0966 - accuracy: 0.9623 - val_loss: 0.1553 - val_accuracy: 0.9361
Epoch 82/100
235/235 [==============================] - ETA: 0s - loss: 0.0842 - accuracy: 0.9663

235/235 [==============================] - 61s 262ms/step - loss: 0.0842 - accuracy: 0.9663 - val_loss: 0.2247 - val_accuracy: 0.9163
Epoch 83/100
235/235 [==============================] - ETA: 0s - loss: 0.0830 - accuracy: 0.9685

235/235 [==============================] - 64s 274ms/step - loss: 0.0830 - accuracy: 0.9685 - val_loss: 0.1498 - val_accuracy: 0.9396
Epoch 84/100
235/235 [==============================] - ETA: 0s - loss: 0.0724 - accuracy: 0.9711

235/235 [==============================] - 62s 263ms/step - loss: 0.0724 - accuracy: 0.9711 - val_loss: 0.2378 - val_accuracy: 0.9123
Epoch 85/100
235/235 [==============================] - ETA: 0s - loss: 0.0747 - accuracy: 0.9702

235/235 [==============================] - 62s 264ms/step - loss: 0.0747 - accuracy: 0.9702 - val_loss: 0.2157 - val_accuracy: 0.9184
Epoch 86/100
235/235 [==============================] - ETA: 0s - loss: 0.0754 - accuracy: 0.9707

235/235 [==============================] - 65s 278ms/step - loss: 0.0754 - accuracy: 0.9707 - val_loss: 0.1884 - val_accuracy: 0.9283
Epoch 87/100
235/235 [==============================] - ETA: 0s - loss: 0.0777 - accuracy: 0.9689

235/235 [==============================] - 63s 268ms/step - loss: 0.0777 - accuracy: 0.9689 - val_loss: 0.1747 - val_accuracy: 0.9308
Epoch 88/100
235/235 [==============================] - ETA: 0s - loss: 0.0728 - accuracy: 0.9706

235/235 [==============================] - 63s 267ms/step - loss: 0.0728 - accuracy: 0.9706 - val_loss: 0.4448 - val_accuracy: 0.8699
Epoch 89/100
235/235 [==============================] - ETA: 0s - loss: 0.0904 - accuracy: 0.9663

235/235 [==============================] - 69s 293ms/step - loss: 0.0904 - accuracy: 0.9663 - val_loss: 0.1765 - val_accuracy: 0.9327
Epoch 90/100
235/235 [==============================] - ETA: 0s - loss: 0.0795 - accuracy: 0.9705

235/235 [==============================] - 62s 266ms/step - loss: 0.0795 - accuracy: 0.9705 - val_loss: 0.2507 - val_accuracy: 0.9069
Epoch 91/100
235/235 [==============================] - ETA: 0s - loss: 0.0728 - accuracy: 0.9711

235/235 [==============================] - 63s 267ms/step - loss: 0.0728 - accuracy: 0.9711 - val_loss: 0.2735 - val_accuracy: 0.9088
Epoch 92/100
235/235 [==============================] - ETA: 0s - loss: 0.0651 - accuracy: 0.9758

235/235 [==============================] - 65s 278ms/step - loss: 0.0651 - accuracy: 0.9758 - val_loss: 0.1844 - val_accuracy: 0.9286
Epoch 93/100
235/235 [==============================] - ETA: 0s - loss: 0.0659 - accuracy: 0.9740

235/235 [==============================] - 63s 267ms/step - loss: 0.0659 - accuracy: 0.9740 - val_loss: 0.2276 - val_accuracy: 0.9207
Epoch 94/100
235/235 [==============================] - ETA: 0s - loss: 0.0692 - accuracy: 0.9731

235/235 [==============================] - 63s 267ms/step - loss: 0.0692 - accuracy: 0.9731 - val_loss: 0.1805 - val_accuracy: 0.9345
Epoch 95/100
235/235 [==============================] - ETA: 0s - loss: 0.0699 - accuracy: 0.9736

235/235 [==============================] - 70s 299ms/step - loss: 0.0699 - accuracy: 0.9736 - val_loss: 0.2167 - val_accuracy: 0.9231
Epoch 96/100
235/235 [==============================] - ETA: 0s - loss: 0.0712 - accuracy: 0.9733

235/235 [==============================] - 67s 285ms/step - loss: 0.0712 - accuracy: 0.9733 - val_loss: 0.2615 - val_accuracy: 0.9079
Epoch 97/100
235/235 [==============================] - ETA: 0s - loss: 0.0687 - accuracy: 0.9740

235/235 [==============================] - 76s 326ms/step - loss: 0.0687 - accuracy: 0.9740 - val_loss: 0.1636 - val_accuracy: 0.9363
Epoch 98/100
235/235 [==============================] - ETA: 0s - loss: 0.0611 - accuracy: 0.9761

235/235 [==============================] - 71s 304ms/step - loss: 0.0611 - accuracy: 0.9761 - val_loss: 0.2253 - val_accuracy: 0.9211
Epoch 99/100
235/235 [==============================] - ETA: 0s - loss: 0.0651 - accuracy: 0.9744

235/235 [==============================] - 73s 313ms/step - loss: 0.0651 - accuracy: 0.9744 - val_loss: 0.2516 - val_accuracy: 0.9134
Epoch 100/100
235/235 [==============================] - ETA: 0s - loss: 0.0606 - accuracy: 0.9766

235/235 [==============================] - 70s 298ms/step - loss: 0.0606 - accuracy: 0.9766 - val_loss: 0.2481 - val_accuracy: 0.9153


In [52]:
# Perform prediction
from sklearn.metrics import accuracy_score
test_preds = model.predict(sequence_test)

313/313 [==============================] - 10s 22ms/step


In [58]:
# Print predictions
print(test_preds)

[[2.4423380e-06 1.5146946e-11 1.8166912e-07 9.9999732e-01]
 [5.0586678e-08 1.1777139e-06 9.7135240e-01 2.8646357e-02]
 [3.0340531e-01 6.9659448e-01 1.6936561e-07 4.7643067e-09]
 ...
 [9.9999803e-01 9.2646405e-07 2.8643925e-12 9.4428378e-07]
 [1.6292623e-04 9.9983668e-01 3.5882795e-07 3.5367671e-11]
 [1.2521541e-08 2.8557284e-07 9.6198845e-01 3.8011149e-02]]


The obtained predictions needs to be converted into one among {1,2,3,4}

In [54]:
# Converting predictions
preds=[]
for i in range(len(target_test)):
  if test_preds[i][0]>=test_preds[i][1]:
    if test_preds[i][0]>=test_preds[i][2]:
      if test_preds[i][0]>=test_preds[i][3]:
        preds.append(0)
  if test_preds[i][1]>=test_preds[i][0]:
    if test_preds[i][1]>=test_preds[i][2]:
      if test_preds[i][1]>=test_preds[i][3]:
        preds.append(1)
  if test_preds[i][2]>=test_preds[i][1]:
    if test_preds[i][2]>=test_preds[i][0]:
      if test_preds[i][2]>=test_preds[i][3]:
        preds.append(2)
  if test_preds[i][3]>=test_preds[i][1]:
    if test_preds[i][3]>=test_preds[i][2]:
      if test_preds[i][3]>=test_preds[i][0]:
        preds.append(3)

In [55]:
# Converted predictions
target_test

30000    3.0
30001    2.0
30002    1.0
30003    2.0
30004    1.0
        ... 
39995    3.0
39996    2.0
39997    0.0
39998    1.0
39999    2.0
Name: Sensor_1, Length: 10000, dtype: float64

30000    3.0
30001    2.0
30002    1.0
30003    2.0
30004    1.0
        ... 
39995    3.0
39996    2.0
39997    0.0
39998    1.0
39999    2.0
Name: Sensor_1, Length: 10000, dtype: float64

In [56]:
# Accuracy score
accuracy_score(target_test,preds)

0.9108